### PR TITLE
Add write to tx registers in init_network, autopep8

### PR DESCRIPTION
**Pull request by peter-madigan**

### CODE REVIEW

**Comment by mualem** [comment]
I think this is part of it.  This should make it more reliable to establish communication with the differential readout.
I think the more fundamental problem I'm seeing is that I'm not able to configure with a chip_id!=1, and if I run an init_network it seems to derail a working system, even if I'm not trying to change the chip_id.

**Comment by mualem** [comment]
I made some tests with it, since you were so kind to supply the quick fixes.  I'm going to have to head out now though.

**Comment by peter-madigan** [comment]
No problem. Does this happen when using the default values in the script or
with a provided configuration file?
If it's when using a configuration file, can you send me what you
are using? I'd like to see if it is just something simple.

**Comment by mualem** [comment]
It happens with the defaults in the script.

Leon Mualem
Lauritsen Lab MC 356-48
Caltech 1200 E. California Blvd.
Pasadena, CA 91125
1 (626) 817-3459
________________________________

**Pull request merged**
