### PR TITLE
Modified enable_miso/mosi register or config calls in controller.py to enable_piso/posi

### PR DESCRIPTION
**Pull request by mualem**
to make more compatible with v2b registers. Only enable_miso_differential
remained unchanged, as it is the only one that does not have an analog in
the v2b config. All others changed enable_m became enable_p.

### CODE REVIEW

**Comment by mualem** [comment]
If it's not obvious. This change would break any v2 asic config using init_network and possibly other methods as well, since there are not enable_piso/posi registers for v<2b

**Comment by peter-madigan** [comment]
@mualem @russellphysics Can you test this to make sure it works with both v2 and v2b?

**Comment by mualem** [comment]
Looks like some progress.
The new versions work with my version2 code.
I still have problems with v2b, but I made quite a few changes
while trying to debug, so I might still have some bad config in there.
For example, my v2 code was broken since I had to force differential=False
so it would avoid the nonexistent enable_piso_differential for v2b.

I'll poke at it some more now, and maybe we can discuss a little later.

Leon Mualem
Lauritsen Lab MC 356-48
Caltech 1200 E. California Blvd.
Pasadena, CA 91125
1 (626) 817-3459
________________________________

**Comment by peter-madigan** [comment]
@mualem #248 should fix the issues you were having with `init_network`

**Pull request merged**
