### PR TITLE
Fix issue #119: ZMQ packet parsing for python2

### PR DESCRIPTION
**Pull request by peter-madigan**
Fixed bug that raised an error when encoding packets while using python 2.
Adds a test for encoding / decoding ZMQ IO messages.

### CODE REVIEW

**Comment by samkohn** [comment]
Looks good to me

**Comment by peter-madigan** [comment]
Is the CI set up and running with this "new" repo? I don't see the little box here in the PR dialog.

**Comment by samkohn** [comment]
I will check on that in ~an hour when I get back to the lodge (I'm just working off my phone right now)

**Comment by peter-madigan** [comment]
OK no rush.

**Comment by peter-madigan** [comment]
It looks like there is a travis-CI webhook enabled.

**Comment by samkohn** [comment]
Travis-ci should be testing the pull request. I do not know why it is not. Can you try making a new pull request and/or pushing a new commit to this one?

New pull-request idea: update the README build status icon to ``[Build Status](https://travis-ci.com/larpix/larpix-control)``

**Comment by peter-madigan** [comment]
OK that time it worked.

**Pull request merged**
