### PR TITLE
Issue #145 / parse new zmq data formats

### PR DESCRIPTION
**Pull request by peter-madigan**
@samkohn, I've implemented a reader for our new and improved "Igor dataserver format". Basically, the new format includes a header word (8-bytes) included with every transmission. The first two bytes are reserved for versioning and the third is reserved for the message type (e.g. timestamp, data, others?). The remaining bytes are particular to the message type. The message "payload" can then be any number of 8-byte words following the header (so we are not necessarily stuck with an 8-byte timestamp at this point). I've implemented this and added a basic test.

I don't think that this format significantly impacts the data rate - only one header message is sent per DAQ board fifo flush (1024 packets). So, if the data rate is high, the headers are an insignificant fraction of the data.

Since it requires #140 for the Timestamp package, I've submitted a PR now, but I will update this once that gets merged in. I also haven't checked python 2 compatibility yet. But I have tested it with a test DAQ board with an upgraded dataserver and it gets all the endian-ness correct.

### CODE REVIEW

**Comment by peter-madigan** [comment]
Of course it doesn't work with python 2, I'm working on a fix now.

**Comment by peter-madigan** [comment]
@samkohn I've made a message format for the new DAQ board format, but it's very ugly. I had a rough time with the byte formatting between python 2 and 3. If you have suggestions to make this cleaner, I will implement them.

**Comment by peter-madigan** [comment]
@samkohn much better, thanks.
I'll wait for you to merge in your Timestamp packet and then make updates accordingly.
Since the zmq io messages don't contain the upstream/downstream packets, I won't include them in the formatter - unless you think otherwise.

**Comment by samkohn** [comment]
Yeah don't include DirectionPackets - Dan said to remove them and just assign the ``direction`` field for every packet so pull request #140 no longer includes them. But that's not necessary to include in the binary format because the IO object knows whether it's reading or writing.

I plan on merging #140 on Monday or Tuesday.

**Comment by samkohn** [comment]
Merged #140 so you're all set to work with the TimestampPacket objects!

**Comment by peter-madigan** [comment]
This should be good to merge once the tests are run.

**Comment by peter-madigan** [comment]
Actually I should add a docs section on this.

**Pull request merged**
